events {

}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80 default_server;
        server_name _;

        location / {
            return 200 'server is up';
            add_header Content-Type text/plain;
        }
    }
    # UI APP

    server {
        listen 443 ssl;
        server_name adsphere.software www.adsphere.software;

        ssl_certificate /etc/nginx/certs/live/adsphere.software/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/live/adsphere.software/privkey.pem;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            root /var/www/adsphere-ui/browser;
            try_files $uri $uri/ /index.html;
        }

    }

    # API
    server {
        listen 443 ssl;
        server_name api.adsphere.software;
        ssl_certificate /etc/nginx/certs/live/api.adsphere.software/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/live/api.adsphere.software/privkey.pem;

        location / {
            proxy_pass http://adsphere-backend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # ADMIN
    server {
        listen 443 ssl;
        server_name admin.adsphere.software;
        ssl_certificate /etc/nginx/certs/live/admin.adsphere.software/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/live/admin.adsphere.software/privkey.pem;

        location / {
            root /var/www/adsphere-admin;
            try_files $uri $uri/ /index.html;
        }

    }
}
